name: Build and Release SFML Game

on:
  push:
    tags:
      - 'v*'  # Ex: v1.0.0, v2.1.3

jobs:
  build:
    runs-on: windows-latest

    env:
      MINGW_URL: https://github.com/brechtsanders/winlibs_mingw/releases/download/12.2.0-14.0.6-ucrt-r3/winlibs-x86_64-posix-seh-gcc-12.2.0-mingw-w64ucrt-14.0.6-r3.zip
      SFML_URL: https://github.com/SFML/SFML/releases/download/3.0.0/SFML-3.0.0-windows-mingw-11-64-bit.zip

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MinGW
        run: |
          curl -L %MINGW_URL% -o mingw.zip
          7z x mingw.zip -oC:\mingw
          echo "C:\mingw\mingw64\bin" >> $GITHUB_PATH

      - name: Download SFML
        run: |
          curl -L %SFML_URL% -o sfml.zip
          7z x sfml.zip -osfml

      - name: Create build directory
        run: mkdir build

      - name: Compile game
        run: |
          g++ src/main.cpp -IC:/sfml/include -LC:/sfml/lib -lsfml-graphics -lsfml-window -lsfml-system -o build/my-game.exe

      - name: Copy DLLs
        run: copy sfml/bin/*.dll build/

      - name: Create release package
        run: |
          mkdir dist
          powershell Compress-Archive -Path build\* -DestinationPath dist\my-game.zip

      - name: Upload artifact (build only)
        uses: actions/upload-artifact@v4
        with:
          name: my-game-artifact
          path: dist/my-game.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: dist/my-game.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
